"""add local_media_path column

Revision ID: 50924fbd8e5d
Revises: d279367b8068
Create Date: 2025-07-17 05:01:56.859457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50924fbd8e5d'
down_revision = 'd279367b8068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_media_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('local_media_path')

    # ### end Alembic commands ###
