"""empty message

Revision ID: 575c7d526100
Revises: 5368e9d16126
Create Date: 2025-07-18 04:03:54.574238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575c7d526100'
down_revision = '5368e9d16126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('is_public')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
