"""Add client-specific workout customizations

Revision ID: 8bd34b1e1201
Revises: 575c7d526100
Create Date: 2025-08-09 07:22:12.098379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd34b1e1201'
down_revision = '575c7d526100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_exercise_customization',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('custom_sets', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('substitute_exercise_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['program_assignment.id'], name=op.f('fk_client_exercise_customization_assignment_id_program_assignment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_exercise_customization'))
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('media_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('local_media_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('bodyPart',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('target',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('equipment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('program_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('enabled_days', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('day_customizations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_assignment', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('day_customizations')
        batch_op.drop_column('enabled_days')
        batch_op.drop_column('custom_name')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('equipment',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('target',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bodyPart',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('local_media_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    op.drop_table('client_exercise_customization')
    # ### end Alembic commands ###
